import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';


import {
    ShowFormErrorsComponent, 
    PicPreviewComponent, 
    PhoneRingerComponent,
    ContactSearchModalComponent,
    FormGetInfoComponent,
    PrivateMessagingComponent,
    IncomingCallModalComponent,
    PhoneCallComponent,
    PhoneLineInvitationModalComponent,
    PhoneCallActionPopoverComponent,
    CreateNetcastModalComponent,
    CreateMeetingModalComponent,
    EditNetcastModalComponent,
    CustomerPbxInfoComponent,
    EditAvatarPopoverComponent,
    EditContactModalComponent,
    EditMeetingModalComponent,
    FormCustomerPbxComponent,
    MeetingAttendeeComponent,
    MeetingDetailsComponent,
    MeetingInviteComponent,
    MeetingItemComponent,
    OutgoingCallDialogComponent,
} from './components/index';

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        ReactiveFormsModule,    
        IonicModule,
      ],
    declarations: [
        ShowFormErrorsComponent, 
        PicPreviewComponent, 
        PhoneRingerComponent,
        ContactSearchModalComponent,
        FormGetInfoComponent,
        PrivateMessagingComponent,
        IncomingCallModalComponent,
        PhoneCallComponent,
        PhoneLineInvitationModalComponent,
        PhoneCallActionPopoverComponent,
        CreateNetcastModalComponent,
        CreateMeetingModalComponent,
        EditNetcastModalComponent,
        CustomerPbxInfoComponent,
        EditAvatarPopoverComponent,
        EditContactModalComponent,
        EditMeetingModalComponent,
        FormCustomerPbxComponent,
        MeetingAttendeeComponent,
        MeetingDetailsComponent,
        MeetingInviteComponent,
        MeetingItemComponent,
        OutgoingCallDialogComponent,
    ],
    exports: [
        ShowFormErrorsComponent, 
        PicPreviewComponent, 
        PhoneRingerComponent,
        ContactSearchModalComponent,
        FormGetInfoComponent,
        PrivateMessagingComponent,
        IncomingCallModalComponent,
        PhoneCallComponent,
        PhoneLineInvitationModalComponent,
        PhoneCallActionPopoverComponent,
        CreateNetcastModalComponent,
        CreateMeetingModalComponent,
        EditNetcastModalComponent,
        CustomerPbxInfoComponent,
        EditAvatarPopoverComponent,
        EditContactModalComponent,
        EditMeetingModalComponent,
        FormCustomerPbxComponent,
        MeetingAttendeeComponent,
        MeetingDetailsComponent,
        MeetingInviteComponent,
        MeetingItemComponent,
        OutgoingCallDialogComponent,
    ]
})
export class SharedModule { }